### ISSUE TITLE
Visão geral das cadeiras

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#1]
Falta para:

- [x] Prog1
- [x] Prog2
- [x] EDA
- [x] Leda
- [x] Cálculo 1

**Comment by joseims** [comment]
Acho que deveria colocar um local para exercicios e outro pra aulas/slides, caso alguem queira fazer o upload e não colocar o link, do mesmo jeito que tem pros leites

**Comment by thayannevls** [comment]
Oi @joseims, pensei nisso só fiquei na dúvida se os arquivos podem ter tamanho mto grande pro github

**Comment by SpinnelSun** [comment]
O GitHub permite arquivos de até 100MB e o repositório tem que ocupar, no máximo, 1GB.

**Comment by hericlesme** [comment]
@thayannevls o que acha dessas informações serem coletadas a partir dos objetivos gerais e específicos das disciplinas?

**Comment by thayannevls** [comment]
@hericlesme seriam aquelas info do controle acadêmico?

**Comment by hericlesme** [comment]
@thayannevls Yep. Reformulá-las pra ficar mais amigável pode ser uma boa

**Comment by FannyVieira** [comment]
Se não ficar tão formal, acho que é legal sim, mas acho que seria mais bacana se fosse mais como um mural do que uma pessoa que já pagou a cadeira pensa sobre ela, é algo mais próximo da realidade de todos.

**Comment by thayannevls** [comment]
Também queria que fosse algo assim Fanny, talvez pudessémos dar iniciada em algum pra seguir como exemplo.
