### ISSUE TITLE
Relatar aplicação em visão geral de IC

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#100]
Escrever em visão geral de Introdução a Computação como o assunto ensinado se aplica no curso e na vida real de cientista de computação, relatando a importância da cadeira.

**Comment by guimcarneiro** [comment]
Trabalhando nisso.

**Comment by SpinnelSun** [comment]
@guimcarneiro boa! Vou colocar como WIP.
