### ISSUE TITLE
Adicionar resumos de FMCC1

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#106]
Estamos precisando de resumos de FMCC1 já há algum tempo. Nossos *maintaners* não cursaram a disciplina então precisamos que alunos que tenham entrado no curso já na nova grade resolvam essa *issue*. Os resumos devem ser disponibilizados preferencialmente em formato `markdown`.

**Comment by emys-alb** [comment]
Alguém poderia me ajudar com o markdown, nunca ouvi falar.

**Comment by emys-alb** [comment]
@alvesmatheus me ajudou agora, vou fazer.

**Comment by alvesmatheus** [comment]
Closed via #296.
