### ISSUE TITLE
ementas de fmcc1 diferentes

### ISSUE THREAD

**Issue by jonathantvrs** [OpenDevUFCG/Tamburetei#110]
Pessoal, as ementas dadas por CW e Eanes no P1 são um pouco diferentes. Como fazemos com essa issue #103 que @thayannevls colocou?

**Comment by jonathantvrs** [comment]
add a label de discussão alguém

**Comment by hericlesme** [comment]
Mas FMCC1 não tem assuntos gerais? Definidos na própria disciplina? Não sei exatamente como é a diferença entre a ementa entre eles que você fala, mas pensando do ponto de vista de cadeira, acredito que eles não podem fugir do objetivo dela. Daí, pelos menos assuntos em comum nós temos

**Comment by FannyVieira** [comment]
Eu acho que nāo é colocar a ementa do modo formal como a gente vê na página da disciplina, é mais uma visāo geral do que a cadeira se propõe, como hericles falou, acredito que assim seja facil mesclar o conteudo de ambas

**Comment by FannyVieira** [comment]
Mas vc chamou atençāo pra um ponto interessante, que é de definir um modelo pra essaementa

**Comment by jonathantvrs** [comment]
Sim sim, de fato. Seria interessante pra deixar claro que existe essa diferença porque ambos ensinam coisas que o outro não ensina

**Comment by hericlesme** [comment]
@FannyVieira @jonathantvrs Além disso, o plano de curso tem as informações dos componentes curriculares. Dá uma olhada [aqui](https://drive.google.com/file/d/0B_94ash-JfI8OEJIX3hfdFFFNkU/view?usp=sharing) na página 51.

**Comment by FannyVieira** [comment]
Show hericles, podemos usar isso pra popular as ementas

**Comment by FannyVieira** [comment]
Da pra criar issue tb pra o povo transcrever as informacoes de um modo X que precisa ser discutido, pra esse markdown

**Comment by hericlesme** [comment]
@FannyVieira aproveitando a ocasião, tu acha que disponibilizar o PPC em algum lugar no README é uma boa?

**Comment by FannyVieira** [comment]
Nāo sei se no Readme, no contributing fosse melhor, talvez

**Comment by jonathantvrs** [comment]
ou criar um markdown específico pro link?

**Comment by jonathantvrs** [comment]
a ideia é que fique o mais na cara possível, pq é o doc que permeia todo o curso

**Comment by hericlesme** [comment]
@FannyVieira @thayannevls oq acham desse ultimo comment?

**Comment by SpinnelSun** [comment]
O que eu estava fazendo durante a padronização das cadeiras do 1º período era que o `visaoGeralEDicas.md` tivesse três campos: Ementa, Visão Geral e Dicas. 

Em **Ementa**, lista-se os tópicos que são descritos no documento da disciplina (dá pra obter pelo Controle Acadêmico, na seção "Currículo). Esses são os assuntos formais dos quais o professor não pode fugir, quaisquer outros tópicos são extras e não cabe formalizar porque há rotação de professores nas disciplinas, etc. 

Em **Visão Geral**, caberia melhor essa questão de assuntos extras, já que coisas que são bem provindas de experiência mesmo. Além de ser onde se descreve no que a cadeira impacta na carreira e tal. Lembrando que temos regras bem firmes sobre citar professores e tal. Em **Dicas**, é bem autoexplicativo.

**Comment by thayannevls** [comment]
Pelo que vi da discussão, seria bom no `CONTRIBUTING.md` ter um tópico explicando o `visaoGeralEDicas.md` da mesma maneira que @SpinnelSun falou aqui e adicionar esse documento que @hericlesme citou nesse tópico, ressaltando que a ementa deve ser feita com base nele.
