### ISSUE TITLE
Melhorar "Como Contribuir" do CONTRIBUTING.md

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#112]
O guia em "Como Contribuir" já começa usando comandos do git, isso dificulta contribuintes que nunca tiveram experiência com github. Seria ideal adicionar o link de um tutorial já existente ou criar um que explique:
- Como dar fork
- Como baixar usando github desktop ou por linha de comando
- Fazer uma alteração localmente ou pela interface do github(em caso de markdowns)
- Abrir uma PR
- Extra: Atualizar seu fork

Essa task pode ser quebrada em partes caso decidam fazer um tutorial.

**Comment by jonathantvrs** [comment]
@thayannevls não seria interessante fazer um video de como contribuir com o projeto? mostrando cada tópico desse? na minha opinião tutoriais de git deixam iniciantes um pouco confusos. O video poderia ser hospedado no drive do OpenDev e adicionaria o link no CONTRIBUTING o que acha?

**Comment by jonathantvrs** [comment]
poderia até ter os tutoriais, mas colocaria esse vídeo para deixar mais claro caso alguém tivesse dúvida

**Comment by SpinnelSun** [comment]
Eu gostei da ideia do vídeo, mas como nós não temos muito tempo até a Semana do Fera... O que vocês acham de tornar o CONTRIBUTING.md mais *clean* nessa parte do passo-a-passo da contribuição (só explicando o flow que a gente usa)? Poderíamos criar um STARTING_WITH_GIT.md que seria linkado lá e bem mais detalhado, explicando desde como instalar o git até como criar a PR.

**Comment by thayannevls** [comment]
O vídeo é uma ideia boa para se ter no futuro, gostei :).

Sobre o tutorial, tava falando com @JoseRenan e ele também tá precisando disso no glossário, acho que uma solução boa @SpinnelSun , seria esse ` STARTING_WITH_GIT.md` ficar no repositório **OpenDevUFCG/OpenDevUFCG** em markdown mesmo e ser mostrado no site. Também poderia ter outros tutoriais.

Pra adicionar no site não é difícil porque a framework que estamos usando já tem essa opção de visualizar markdown no site, então seria só fazer o tutorial. O que acham?

**Comment by jonathantvrs** [comment]
Boa ideia

**Comment by SpinnelSun** [comment]
Ah, melhor ainda, acho que realmente tem que ser bem central já que todos os repositórios vão precisar em certo nível. Estou fazendo umas modificações no CONTRIBUTING.md pra melhorar o que foi discutido em #110 e vou deixar ele mais clean nessa parte para referenciarmos essa parte de git por fora.

**Comment by thayannevls** [comment]
Beleza! Vou transferir essa issue pro outro repositório então.

**Comment by SpinnelSun** [comment]
@thayannevls isso aqui fecha já que o "tutorial git" vai ser externo?

**Comment by thayannevls** [comment]
Sim, sim @SpinnelSun
