### ISSUE TITLE
Implementações em Alloy de Lógica para Computação

### ISSUE THREAD

**Issue by SpinnelSun** [OpenDevUFCG/Tamburetei#13]
<p align="justify">A quantidade de material sobre Alloy disponível na internet é pequena, então ter acesso a projetos antigos ajuda muito quem está tendo seu primeiro contato com a linguagem. Como as especificações são renovadas a cada período, esse acesso não acarretará em casos de cópia.</p>

<p align="justify">A ideia é, basicamente, caçar implementações de projetos em Alloy (não só da disciplina) e linkar os repositórios encontrados para facilitar a busca de material.</p>

**Comment by thayannevls** [comment]
Acho que a gente teria que pedir pros donos do repositórios concordarem, se tu conhecer alguém ai :)

**Comment by FannyVieira** [comment]
Concordo @SpinnelSun , eles me ajudaram bastante também, acho que o pessoal do nosso período não tem problema em compartilhar, mas vamos perguntar.

**Comment by LukeHxH** [comment]
Eu concordo em disponibilizar o do meu grupo =)

Vou abrir uma PR com o meu projeto

**Comment by SpinnelSun** [comment]
Sim sim, vou começar a "caçar" o pessoal que tem os projetos organizados e disponíveis.

**Comment by SpinnelSun** [comment]
Criei o diretório pra Lógica, @FannyVieira e @LukeHxH já conto com o link de vocês lá rs

**Comment by FannyVieira** [comment]
Botei amore

**Comment by hericlesme** [comment]
@SpinnelSun falou comigo ontem, disponibilizo o nosso também.

**Comment by kaiokassiano** [comment]
Oi pessoal,

Disponibilizo a implementação [1] do meu grupo de quando paguei a disciplina.
Parabéns a todos pela iniciativa.

[1] https://github.com/kaiokassiano/gerenciamento-condominio
