### ISSUE TITLE
Relatar aplicações de Laboratório de Organização e Arquitetura de Computadores 

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#131]
Escrever em Visão Geral de Laboratório de Organização e Arquitetura de Computadores sobre como os assuntos estudados nessa disciplina se aplicam ao curso e à vida profissional do Cientista da Computação.

**Comment by alvesmatheus** [comment]
Reformulação da #160 inclui essa *issue*.
