### ISSUE TITLE
Adicionar leite para Cálculo 1.

### ISSUE THREAD

**Issue by dfquaresma** [OpenDevUFCG/Tamburetei#140]
É interessante adicionar provas antigas de Cálculo 1 para dar ajudar os estudar daqueles que estão pagando a disciplina. Além da adição do material, é importante atualizar o [readme](https://github.com/OpenDevUFCG/Tamburetei/blob/master/calculo1/README.md) também.

**Comment by arrudacaio** [comment]
Existe essa pasta do google drive feita por um monitor de cálculo 1 da UFCG  e foi disponibilizada no grupo de Cálculo 1 no facebook : 
https://drive.google.com/drive/folders/1lVZSXtxi0V3bX_ocKgseFmdgWVgwPP29

**Comment by thayannevls** [comment]
Opa @arrudacaio que legal! Tu gostaria de adicionar esse link nos leites? Ou prefere que outra pessoa façam?

**Comment by arrudacaio** [comment]
Pode deixar que eu faço, tentar pegar o jeito do git kk

**Comment by thayannevls** [comment]
Qualquer dúvida chama no channel do discord :)

**Comment by LukeHxH** [comment]
Agora que foi adicionado, essa issue pode ser fechada?

**Comment by thayannevls** [comment]
Por mim sim!
