### ISSUE TITLE
Transformar resumos de Redes em .md

### ISSUE THREAD

**Issue by SpinnelSun** [OpenDevUFCG/Tamburetei#153]
Os únicos resumos que não estão no próprio repositório são os de Redes. Apesar do material linkado ser bem completo, estão em `.doc` e, portanto, pesariam bastante. Sintam-se convocados a transformar tudo em `.md`. :balloon:

**Comment by thayannevls** [comment]
Foi completa essa task?

**Comment by SpinnelSun** [comment]
Foi sim, pensei que tinha fechado automaticamente, sorry.
