### ISSUE TITLE
Modificar script de criação de disciplinas para adicioná-las ao sumário do README

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#156]
Seria interessante que o script `scripts/create_folder_structure` perguntasse o período da disciplina e adicionasse automaticamente a disciplina no sumário do README.

**Comment by thayannevls** [comment]
Como tem algumas disciplinas que não tem período definido, talvez seja melhor deixá-las apenas por ordem alfabética

**Comment by tarsojabbes** [comment]
Essa issue está desatualizada porque o sumário no README deixará de existir segundo a issue #390.
