### ISSUE TITLE
Adicionar visão geral e dicas para LOAC

### ISSUE THREAD

**Issue by lucasmedeiros** [OpenDevUFCG/Tamburetei#160]
A disciplina de Laboratório de Organização e Arquitetura de Computadores ainda não teve seu *visaoGeralEDicas.md* completamente preenchido. Se você cursou (ou está cursando) essa disciplina, poderia no ajudar com isso?

- [X] Preencher a seção de **Ementa** em *visaoGeralEDicas.md*.
- [X] Preencher a seção de **Visão Geral** em *visaoGeralEDicas.md*.
- [X]  Preencher a seção de **Dicas** em *visaoGeralEDicas.md*.

**Comment by tarsojabbes** [comment]
Esse conteúdo já se encontra no site :)
