### ISSUE TITLE
Adicionar implementações para Projeto de Software

### ISSUE THREAD

**Issue by lucasmedeiros** [OpenDevUFCG/Tamburetei#161]
Criar a pasta `psoft/implementacoes` para adicionar exemplos do que é ensinado na disciplina. O que eu acho que caberia um exemplo de implementação:

- [ ] Callbacks - JS
- [ ] Promises - JS.
- [ ] Await e async - JS
- [ ] Fetch API - JS.
- [ ] Módulos introduzidos a partir do ES6 - JS
- [ ] Estilização utilizando Grid - CSS.
- [ ] Estilização utilizando Flexbox - CSS.
- [ ] Novas tags semânticas - HTML

Além disso, a falta de exemplos de aplicações (conforme discutido em #45) é um problema para os alunos da disciplina, assim, seria interessante linkar alguns exemplos como:

- [ ] Lista de tarefas
- [X] App de notas
- [ ] Blog simples
- [ ] Mini loja virtual, com carrinho e pesquisa de produtos
- [ ] Formulários de registro e login de usuários

**Comment by FannyVieira** [comment]
Relacionado a discussāo #43 

Como em html5 surgiram algumas tags com uma semântica bem definida, também acho que faz sentido discutir sobre elas.

**Comment by FannyVieira** [comment]
Nesse caso, eu fecho a de resumos, @LukeHxH ?

**Comment by FannyVieira** [comment]
Acho que faz sentido deixar ao menos pro tópico de padrāo de projeto

**Comment by LukeHxH** [comment]
@FannyVieira, acho que não precisa fechar a de resumos, porque ainda acho que cabe fazer resumos sobre padrões de projetos. Só editar o nome e a descrição mesmo.

**Comment by matheusps** [comment]
@LukeHxH talvez exemplos com react, vue, angular 🤔? Acho que deixar no [codesandbox](https://codesandbox.io/) seria uma boa tbm. (tem haver com a #45)

**Comment by LukeHxH** [comment]
@matheusps Acho que os frameworks entram no mesmo caso que foi discutido [aqui](https://github.com/OpenDevUFCG/Tamburetei/issues/43#issuecomment-478233343). Para não ficar tão grande, creio que seria melhor colocar links para cursos básicos/intermediários para que eles possam dar uma estudada para fazer o projeto. As implementações que sugeri nessa issue são de assuntos que estão sendo dados na disciplina e que caem diretamente nas provas, além do projeto. Mas outras sugestões sempre são bem-vindas!

**Comment by thayannevls** [comment]
Gostei muito da ideia de usar o codesandbox pra algumas coisas, @LukeHxH poderia até ser usado pra quando não tem framework tbm

**Comment by tarsojabbes** [comment]
Essa issue será fechada porque está desatualizada para o modelo atual da disciplina.
