### ISSUE TITLE
Problema com script de geração

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/Tamburetei#182]
Encontrei um problema no template criado pelo script de geração de arquivos. Ele está retornando um readme com problema:
 ![](https://media.discordapp.net/attachments/558367708597583873/567007854717042688/unknown.png)

Acho que o correto seria o próprio nome da disciplina.

**Comment by thayannevls** [comment]
Esse problema ainda existe 

cc @lucasecdb

**Comment by alvesmatheus** [comment]
@thayannevls as alterações que @pedroespindula fez não corrigiram isso não?

**Comment by thayannevls** [comment]
@alvesmatheus não, ele tinha botado o format na função errada, ainda tava dando problema :/
