### ISSUE TITLE
Repositório com algumas implementações de provas de LP2

### ISSUE THREAD

**Issue by AntonioNtV** [OpenDevUFCG/Tamburetei#188]
Criei esse repositório com algumas implementações das provas de LP2.
Vou ficar atualizando ele sempre que possivel.

https://github.com/AntonioNtV/provasLP2

**Comment by fanny** [comment]
Oi @AntonioNtV, muito legal tua iniciativa!

O que tu acha de adicionar nos links úteis da pasta de lp2? Facilitaria e ajudaria outras pessoas encontrarem ele.
