### ISSUE TITLE
Implementações de eda

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#2]
Deve ser feito em python ou java, para facilitar quem está pagando a cadeira e não viu muitas linguagens ainda. Pode pegar só um e ajudar

- [x] Bubble sort
- [x] Insertion sort
- [x] Quick sort
- [x] Merge sort
- [x] Count sort
- [x] Busca binária
- [x] Pilha
- [x] Fila
- [x] LinkedList
- [x] Árvore BST

Sugestões de mais algoritmos são aceitos 😄

**Comment by FannyVieira** [comment]
Tem as árvores também, as implementações podiam ser em várias linguagens também, @spinnelsun tem um repositorio bem organizado e completo com essas implementações.

**Comment by thayannevls** [comment]
Se  @SpinnelSun quiser botar o link do repositório dele nos LinksUteis.md :)

**Comment by SpinnelSun** [comment]
Seria interessante unir EDA e LEDA numa pasta só (como P2 e LP2)?

**Comment by FannyVieira** [comment]
Tava pensando nisso tb, eu acho que sim, porque as coisas dessas disciplinas estão bem conectadas.

**Comment by juliobguedes** [comment]
Já eu, discordo. Muitas vezes, como levantado na SACC, os roteiros de LEDA tornam o desenvolvimento mais complicado devido as interfaces e classes vazias. Acho mais intuitivo separar um código ideal, que implementa a teoria dada em EDA, do que manter misturado.

**Comment by juliobguedes** [comment]
Inclusive, me disponho a fazer os códigos de árvores, pilha, fila e lista encadeada.

**Comment by SpinnelSun** [comment]
Como os roteiros são uma atividade avaliativa recorrente todo período, eles são proibidos aqui, @juliobguedes. As implementações indicadas em Links Úteis já não usam as estruturas (como as interfaces/classes vazias) dos roteiros.

**Comment by thayannevls** [comment]
Verdade, não tinha pensado nisso 🤔 , por mim tudo bem. @juliobguedes se você estiver implementando os códigos que você disse, poderia apagar a pasta de LEDA e juntar no nome? 😄

**Comment by thayannevls** [comment]
Feito

**Comment by juliobguedes** [comment]
Guys, me encham o saco nessa, dá tempo fazer durante o recesso, mas sempre rola o risco de esquecer xd só nn faço agora por estar com mtas pendências do lab, então me lembrem dps
