### ISSUE TITLE
Criar Contributing.md

### ISSUE THREAD

**Issue by hericlesme** [OpenDevUFCG/Tamburetei#21]
Até agora, as informações de contribuição estão no README. Isto não é ruim, porque se tornam visíveis. Mas o que acham de adicionar o **CONTRIBUTING.md**? Não é mais adequado para as diretrizes de contribuição?

**Comment by thayannevls** [comment]
Também queria que fosse definido no ** CONTRIBUTING.md** que há uma restrição de upar livros, apostilas ou slides. Materiais como esse o contribuidor deve upar em algum canto que se possa acessar com o link ~como o drive~ e referenciar esse link 

Digo isso porque o github tem um limite de tamanho que pode estourar se a gente ficar upando arquivos grandes demais.

**Comment by thayannevls** [comment]
Também era bom pedir pra quando forem contribuir, avisarem em uma issue ou criarem uma issue e dizendo que vão fazer
