### ISSUE TITLE
Dificuldade no entendimento do README

### ISSUE THREAD

**Issue by marcellasiqueira** [OpenDevUFCG/Tamburetei#227]
Gostaria de contribuir adicionando meus resumos, mas o README não é intuitivo. Devo rodar o script de qualquer maneira ou apenas quando não existe a pasta da disciplina em questão? Se não tiver, deve ser o nome completo da disciplina ou apenas a sigla? Que README.md com {discipline} é esse? 
Quando acesso o Contributing para tentar ter mais informações sobre como contribuir, encontro as mesmas informações que já vi e nada novo. Sempre devo criar uma issue quando quero contribuir com algo que não tem uma issue (exemplo, um novo resumo de SO)? Crio uma nova branch para abrir PR?

**Comment by lucasmedeiros** [comment]
Olá, @marcellasiqueira, muito obrigado pelo interesse em contribuir! :smile: 

Se a disciplina não existir, você pode rodar o script do jeito que está lá e fazer os ajustes que achar necessário na pasta que foi gerada (O `{discipline}` mostrado no `README.md` após a geração é um bug do script, e realmente é uma falha nossa). Normalmente, utilizamos os nomes abreviados das disciplinas (como `tc`, `so`, `eda`, etc.).

O passo-a-passo a respeito de como realizar uma contribuição está descrito na sessão [Como contribuir?](https://github.com/OpenDevUFCG/Tamburetei/blob/master/CONTRIBUTING.md#Como-contribuir) do `Contributing.md`. Resumidamente, você precisa fazer um `fork`, que vai criar uma cópia do nosso repositório para a sua conta, fazer os commits lá (criar uma branch nova nesse repo *forkado* é totalmente opção sua) e submeter a Pull Request. Ao abrir a PR, terá um *mini-template* para ajudar no processo também.

No geral, a gente tenta encorajar ao máximo a contribuição, não precisa ficar com receio de enviar suas alterações ou de cometer algum "erro", existe todo um cuidado na hora da revisão e, caso necessário, as mudanças que a gente vai sugerir sempre virão de maneira totalmente amigável e transparente. Aguardamos seus resumos! :heart:

**Comment by lucasmedeiros** [comment]
Ah, e caso não exista uma issue para o material que você quer adicionar, você pode abrir uma nova tranquilamente. Inclusive, caso ajude, você pode seguir algum dos modelos abaixo:

- [Modelo 1 - novo resumo](https://github.com/OpenDevUFCG/Tamburetei/issues/214)
- [Modelo 2 - nova pasta](https://github.com/OpenDevUFCG/Tamburetei/issues/198)
- [Modelo 3 - adição de leite](https://github.com/OpenDevUFCG/Tamburetei/issues/179)
- [Modelo 4 - correção de algum conteúdo](https://github.com/OpenDevUFCG/Tamburetei/issues/173)
- [Modelo 5 - atualização de conteúdo de alguma disciplina](https://github.com/OpenDevUFCG/Tamburetei/issues/171)

**Comment by thayannevls** [comment]
@marcellasiqueira esse `{discipline}` provavelmente é um bug, ele deveria colocar o nome da disciplina que você quer criar.

Quanto as outras dúvidas, @lucasmedeiros respondeu, caso tenha mais por favor use essa issue pra perguntar! Queremos saber para melhorar nosso readme e contributing.

Vou abrir algumas issues para adicionar as informações que você perguntou aqui
