### ISSUE TITLE
Melhorar README.md e CONTRIBUTING.md

### ISSUE THREAD

**Issue by alvesmatheus** [OpenDevUFCG/Tamburetei#228]
Conforme citado em #227, nosso README não é tão intuitivo quanto pensávamos. Além disso, parte das informações nele contidas são redundantes com nosso CONTRIBUTING. Considerando que o Tamburetei é o repositório da organização mais capaz de absorver os contribuidores "menos experientes", ele precisa ser tão amigável quanto possível.

Sabendo disso, gostaria de estender a discussão da #227 e criar uma lista de coisas que podem ser melhoradas neles (e no repositório como um todo) e ir fazendo essas mudanças de maneira mais "comunitária". A lista abaixo vai ser atualizada conforme forem surgindo sugestões.

- [ ] Melhor explicação do uso do *script* de criação de disciplina.
- [ ] Dividir informações adequadamente entre README e CONTRIBUTING.
- [ ] Criar modelos para *issues* e *pull requests*.

**Comment by thayannevls** [comment]
Irei fazer algumas mudanças ao contributing seguindo esse [modelo](https://ant.design/docs/react/contributing), tendo tópicos resumidos, e explicações extensa direcionadas para Wiki, como: Restrição de upload, nome de disciplina e etc

O que acham?
