### ISSUE TITLE
Atualizar códigos para Python 3.5+

### ISSUE THREAD

**Issue by alvesmatheus** [OpenDevUFCG/Tamburetei#229]
**O saudoso Python 2.7 está às portas da aposentadoria!** O Laboratório de Programação 1 já está adotando o Python 3.x. e, por isso, algumas de nossas implementações estão defasadas quanto à versão.

Portanto, as implementações da disciplina precisam ser modificadas/atualizadas para evitar os erros causados pelo famigerado *deprecated*. Isso vai evitar que vários feras do futuro passem por problemas.

**Comment by marianasn** [comment]
Vou tentar fazer durante a semana ;)
