### ISSUE TITLE
Atualizar implementações em Python Notebooks em Programação I para Python 3.5+

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#240]
Semelhante a #229 que já foi resolvido aqui #239

Precisamos atualizar os [tutorias](https://github.com/OpenDevUFCG/Tamburetei/tree/master/prog1/implementacoes/tutoriais) de programação 1 para python 3.5+, fazendo as mudanças de sintaxes necessárias.

**Comment by marianasn** [comment]
Vou fazer essa (em menos de 7 dias dessa vez)

**Comment by alvesmatheus** [comment]
Não tem pressa, mas desde já muitíssimo obrigado! :penguin:

**Comment by arthurstevam98** [comment]
Opa, se possível gostaria de ajudar com essa issue

**Comment by alvesmatheus** [comment]
Como temos uma boa quantidade de tutoriais, vou dividir entre vocês, tá?

@arthurstevam98 **:**
- [ ] helloWorld.ipynb
- [ ] formatacaoDeStrings.ipynb
- [ ] estruturasDeCondicao.ipynb
- [ ] funcoes.ipynb
- [ ] matrizes.ipynb

@marianasn **:**
- [ ] listas.ipynb
- [ ] estruturasDeRepeticao.ipynb
- [ ] entradaESaida.ipynb
- [ ] dicionarios.ipynb
- [ ] algoritmosOrdenacao.ipynb

Vocês podem abrir PRs separadas e relacionar a essa mesma *issue*. Aproveitando pra dar uma dica: como os Python Notebooks são mais complicadinhos de lidar, eu sugiro que vocês baixem os arquivos, upem numa conta no [Colab Google](https://colab.research.google.com), mudem para Python 3 (em `settings`) e vão editando por lá, depois é só baixar o arquivo editado e substituir. Achei o Colab muito útil pra achar as diferenças de sintaxe de Python 2.7 pra 3.5.

**Comment by alvesmatheus** [comment]
Closed via #257 and #255.
