### ISSUE TITLE
Adicionar materiais para Álgebra Linear

### ISSUE THREAD

**Issue by alvesmatheus** [OpenDevUFCG/Tamburetei#242]
Atualmente não possuímos nenhum material sobre Álgebra Linear e gostaríamos de priorizar essa disciplina, visto que ela é do início de nossa grade curricular atual. Você pode disponibilizar qualquer material da disciplina que ache interessante, mas nossas sugestões são:

- [x] Preencher as seções **Ementa**, **Visão Geral** e **Dicas** em *visaoGeralEDicas.md*.
- [x] Adicionar **links** para materiais de estudo interessantes em *linksUteis.md*.
- [x] Descrever suas **dificuldades** na disciplina e como superá-las em *dificuldadesComuns.md*.
- [x] Adicionar ou descrever **provas antigas** da disciplina em *leites/*.

**Comment by issilva5** [comment]
Estou produzindo e irei adicionar material sobre Álgebra Linear.

**Comment by fanny** [comment]
Muito obrigada @issilva5

**Comment by lucasmedeiros** [comment]
@issilva5 Muito obrigado, posso dar assign?

**Comment by issilva5** [comment]
Pode dar sim.

**Comment by alvesmatheus** [comment]
Closed via #252
