### ISSUE TITLE
Adicionar visão geral e dicas para Banco de Dados I

### ISSUE THREAD

**Issue by alvesmatheus** [OpenDevUFCG/Tamburetei#243]
O *visaoGeralEDicas.md* da disciplina Banco de Dados I já conta com a ementa da disciplina, mas duas seções (**Visão Geral** e **Dicas**) ainda estão vazias. Se você cursou ou está cursando essa disciplina, compartilhe sua perspectiva sobre ela conosco!

**Comment by marianasn** [comment]
Fazendo essa right now :D

**Comment by thayannevls** [comment]
Meu deus, um anjo @marianasn ❤️

**Comment by alvesmatheus** [comment]
Closed via #260.
