### ISSUE TITLE
Adicionar resumos para Análise de Sistemas

### ISSUE THREAD

**Issue by alvesmatheus** [OpenDevUFCG/Tamburetei#245]
Atualmente não possuímos nenhum material sobre Análise de Sistemas e resumos são ferramentas muito úteis para estudar essa disciplina, dada a quantidade considerável de assuntos que ela engloba. Se você cursou ou está cursando Análise de Sistemas, ajude-nos com resumos sobre um ou mais desses temas:

- [x] Processos de Software
- [x] Casos de Uso e *User Stories*
- [x] Diagramas de Classes UML
- [x] Diagramas de Interação UML
- [x] Linguagem OCL
- [x] Diagramas de Máquinas de Estados UML
- [x] Diagramas de Atividades UML

**Comment by dandaramcsousa** [comment]
#287

**Comment by alvesmatheus** [comment]
Closed via #287.
