### ISSUE TITLE
Adicionar visão geral e dicas para Programação II

### ISSUE THREAD

**Issue by alvesmatheus** [OpenDevUFCG/Tamburetei#263]
A disciplina de Programação II ainda não teve seu *visaoGeralEDicas.md* preenchido. Se você cursou (ou está cursando) essa disciplina, poderia nos ajudar com isso? Pode seguir esse [exemplo](https://github.com/OpenDevUFCG/Tamburetei/blob/master/eda/visaoGeralEDicas.md).

- [x] Preencher a seção de **Ementa** em *visaoGeralEDicas.md*.
- [x] Preencher a seção de **Visão Geral** em *visaoGeralEDicas.md*.
- [x] Preencher a seção de **Dicas** em *visaoGeralEDicas.md*.

**Comment by emys-alb** [comment]
Posso fazer esse.

**Comment by alvesmatheus** [comment]
Closed via #285.
