### ISSUE TITLE
Adicionar dificuldades comuns para Teoria dos Grafos

### ISSUE THREAD

**Issue by alvesmatheus** [OpenDevUFCG/Tamburetei#265]
A disciplina de Teoria dos Grafos ainda não tem nenhuma dificuldade comum descrita.

Se você cursou (ou está cursando) essa disciplina, poderia nos contar um pouco sobre sua experiência na disciplina e preencher o *dificuldadesComuns.md*?

**Comment by LeandraOliveiraS** [comment]
Estou fazendo!

**Comment by thayannevls** [comment]
Obrigada @LeandraOliveiraS ! Qualquer dúvida só chamar
