### ISSUE TITLE
Adicionar visão geral e dicas para Teoria dos Grafos

### ISSUE THREAD

**Issue by alvesmatheus** [OpenDevUFCG/Tamburetei#266]
A disciplina de Teoria dos Grafos ainda não teve seu *visaoGeralEDicas.md* completamente preenchido. Se você cursou (ou está cursando) essa disciplina, poderia nos ajudar com isso?

- [X] Preencher a seção de **Ementa** em *visaoGeralEDicas.md*.
- [ ] Preencher a seção de **Visão Geral** em *visaoGeralEDicas.md*.
- [ ]  Preencher a seção de **Dicas** em *visaoGeralEDicas.md*.

**Comment by LeandraOliveiraS** [comment]
Hello, estou fazendo :smile:
