### ISSUE TITLE
Adicionar visão geral e dicas para Introdução à Probabilidade

### ISSUE THREAD

**Issue by alvesmatheus** [OpenDevUFCG/Tamburetei#268]
A disciplina de Introdução à Probabilidade ainda não teve seu *visaoGeralEDicas.md* completamente preenchido. Se você cursou (ou está cursando) essa disciplina, poderia nos ajudar com isso?

- [X] Preencher a seção de **Ementa** em *visaoGeralEDicas.md*.
- [ ] Preencher a seção de **Visão Geral** em *visaoGeralEDicas.md*.
- [X]  Preencher a seção de **Dicas** em *visaoGeralEDicas.md*.

**Comment by issilva5** [comment]
Eu posso concluir o visão geral.

**Comment by thayannevls** [comment]
Ótimo @issilva5 ! Vou atribuir a task a você, sinta-se livre pra pedir ajuda

**Comment by issilva5** [comment]
Pull Request feito em #280

**Comment by alvesmatheus** [comment]
Closed via #280.
