### ISSUE TITLE
Adicionar dificuldades comuns para LOAC

### ISSUE THREAD

**Issue by alvesmatheus** [OpenDevUFCG/Tamburetei#269]
A disciplina de Laboratório de Organização e Arquitetura de Computadores ainda não tem nenhuma dificuldade comum descrita.

Se você cursou (ou está cursando) essa disciplina, poderia nos contar um pouco sobre sua experiência na disciplina e preencher o *dificuldadesComuns.md*?

**Comment by luanabm** [comment]
To fazendo

**Comment by alvesmatheus** [comment]
Closed via #362.
