### ISSUE TITLE
Adicionar dificuldades comuns para OAC

### ISSUE THREAD

**Issue by alvesmatheus** [OpenDevUFCG/Tamburetei#270]
A disciplina de Organização e Arquitetura de Computadores ainda não tem nenhuma dificuldade comum descrita.

Se você cursou (ou está cursando) essa disciplina, poderia nos contar um pouco sobre sua experiência na disciplina e preencher o *dificuldadesComuns.md*?

**Comment by luanabm** [comment]
Fazendo

**Comment by alvesmatheus** [comment]
Closed via #365.
