### ISSUE TITLE
Adicionar dificuldades comuns para Projeto de Software

### ISSUE THREAD

**Issue by alvesmatheus** [OpenDevUFCG/Tamburetei#272]
A disciplina de Projeto de Software ainda não tem nenhuma dificuldade comum descrita.

Se você cursou (ou está cursando) essa disciplina, poderia nos contar um pouco sobre sua experiência na disciplina e preencher o *dificuldadesComuns.md*?

**Comment by luanabm** [comment]
to fazendo

**Comment by alvesmatheus** [comment]
Closed via #365.
