### ISSUE TITLE
Refatorar códigos em python para seguir o PEP8

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#28]
As documentações das [implementações](https://github.com/OpenDevUFCG/Tamburetei/tree/master/prog1/implementacoes) de prog1 não estão seguindo o padrão PEP8. 

Incluir também um guia das melhores práticas em Python no **README.md** da pasta prog1. Eu particularmente amo [esse](https://gist.github.com/sloria/7001839), por ser resumido e simples. Nunca vi um assim em português, talvez possamos traduzir depois.

#3

**Comment by FannyVieira** [comment]
E além de padronizar pra PEP8, é bom padronizar a linguagem, se começou em inglês, faça tudo em inglês, e a legibilidade no geral.

**Comment by SpinnelSun** [comment]
<b>Done!</b>
