### ISSUE TITLE
Implementações de Prog1

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#3]
Como a cadeira P1 é paga com python, todas as implementações tem que ser em python

Algumas que pensei:

- [x] Bubble sort
- [x] Insertion sort
- [x] Selection sort
- [x] Split
- [x] Reverso
- [x] Algum exemplo bom de uso de If & else de sua escolha
- [x] Achar o maior número de uma lista
- [x] Fatorial com recursão
- [x] Somar diagonal principal de uma matriz
- [x] Exemplo usual de dicionário
- [x] Exemplo explicado das estruturas de repetição, For, While, Do while...

Se tiverem mais sugestões, a vontade.

Referencie essa issue na sua PR para nos mantermos atualizados do progresso

**Comment by hericlesme** [comment]
@thayannevls, estou implementando algumas dessas. Vamos utilizar o estilo de documentação de @HenryFilho para as demais?

**Comment by thayannevls** [comment]
Sim, Sim. Achei o estilo de @HenryFilho muito bom, manteria o padrão

**Comment by thayannevls** [comment]
Vou incluir mais alguns

**Comment by hericlesme** [comment]
@thayannevls um exemplo claro de formatação de String é uma boa.

**Comment by SpinnelSun** [comment]
@thayannevls Não seria melhor usar docstrings não? Creio que seria interessante acostumar o pessoal mais inexperiente com a "aparência" dos padrões de documentação já...

**Comment by thayannevls** [comment]
Verdade @SpinnelSun @hericlesme , vou criar uma issue pra refatorar o que se tem e adicionar nas informações que é preciso seguir o padrão
