### ISSUE TITLE
Dificuldade no entendimento de como começar a contribuir

### ISSUE THREAD

**Issue by felipesqra** [OpenDevUFCG/Tamburetei#304]
Aos alunos dos períodos iniciais, o procedimentos que devem ser seguidos para ajudar na contribuição estão muito confusos, sejam por termos com os quais não se tem familiaridade, como "fork", etc, ou pelos próprios passos que devem ser seguidos. Então talvez adicionar um passo a passo mais claro de como começar a contribuir quando se está nos períodos iniciais seja algo útil.

**Comment by vinifarias** [comment]
Fala @felipesqra, realmente não deixamos de uma forma muita clara e tão "visível" em nosso CONTRIBUTING.md o passo a passo para contribuir (já seria uma contribuição sua colocar aí nos comentários sugestões de como melhorar isso :wink:)

Mas nós colocamos em nossa wiki o passo a passo, pode acessá-lo [aqui](https://github.com/OpenDevUFCG/Tamburetei/wiki/Submetendo-uma-Pull-Request).
Recomendo também esse [*post*](https://dev.to/opendevufcg/contribuindo-para-projetos-open-source-com-github-3i76) do nosso blog sobre contribuições em projetos open source.

**Comment by tarsojabbes** [comment]
Essa tópico já é abordado na issue #390 mas adiciona pontos interessantes de serem levantados no nosso README e no site
