### ISSUE TITLE
O formato CamelCase está bom?

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#37]
Queria perguntar enquanto ainda há tempo kkkk se o formato CamelCase pros arquivos está bom, ou se mudaria para underscore

CamelCase: `visaoGeralEDicas.md`

underscore: `visao_geral_e_dicas.md`

**Comment by FannyVieira** [comment]
Em md thayanne, eu vejo o pessoal usando o `-`, por exemplo, nos temas do hugo que você faz posts usando md, eles usariam `visao-geral-e-dicas.md`, eu acho legal assim, mas isso é bem subjetivo kkkk

**Comment by FannyVieira** [comment]
Eu tava lendo sobre "filename conventions" era em html, mas achei isso aqui: 

> Using words separated by hyphens can have some help in SEO because search engines read the URLs as well.

** SEO = Search Engine Optimization
Link referência: https://www.lifewire.com/naming-html-files-3466503

**Comment by JuanBarros2** [comment]
camelcase é um amor :heart:

**Comment by thayannevls** [comment]
Okay galers kkk camelcase
