### ISSUE TITLE
Quais seriam as dificuldades mais comuns em Programação 1?

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#4]
Acho que uma das maiores dificuldades é aprender a ser autodidata e também ver que estudar para programação é muito diferente de outras disciplinas. Apesar que eu não sei dizer o que mais pode ajudar a superar essas dificuldades.

Sugestões?

**Comment by hericlesme** [comment]
@thayannevls estou pesquisando sobre isto, inclusive com os professores para obter um resultado mais objetivo quanto à isto. Tanto de **P1/LP1** quanto **P2/LP2**.

**Comment by thayannevls** [comment]
Okay @hericlesme, qualquer update mando por aqui

**Comment by FannyVieira** [comment]
Acho que tentar instigar a curiosidade entre eles é um bom ponto, por exemplo, tem alguns sites pra você programar enquanto joga, acho que isso é uma das coisas que a gente pode explorar.

**Comment by hericlesme** [comment]
@thayannevls @FannyVieira. Acabei de obter alguns resultados de profs... Aparentemente, a dificuldade do aluno de P1 é **"entender a situação em que o código precisa passar mais de 1 vez pela mesma linha. Ou seja, a capacidade de pensar a frente para realizar a codificação."**.
No caso do aluno de P2, **"a dificuldade de programar está em separar classe (código) de objeto (execução). A parte de modelar esta em entender os objetos como entidades isoladas, que se comunicam para atingir o seu trabalho."** Resumindo... A decisão de que classes fazer, que métodos, atributos...

**Comment by thayannevls** [comment]
No caso de P1, seriam as repetições?

**Comment by hericlesme** [comment]
@thayannevls basicamente isto. Falei com mais professores sobre isto e a resposta que eu tive desta vez foi que existem várias dificuldades em P1. Do ponto de vista geral, seria entender o "pensar computacional". E especificamente, as iterações sempre são um problema recorrente.

**Comment by FannyVieira** [comment]
@hericlesme comenta tua ideia aqui

**Comment by hericlesme** [comment]
@OpenDevUFCG/tamburetei, conseguimos destacar algumas dificuldades na disciplina. Mas aí vem a questão. **Como resolver?** Basicamente minha ideia é fazer uma página onde os alunos pudessem ver de forma intuitiva, e além de ver, interagir com a explicação. A ideia eu tirei de um livro meu de JS, eu levarei ele amanhã pra mostrar pra vocês, ou até por as fotos aqui pra vocês verem...

**Comment by thayannevls** [comment]
@hericlesme comentaram na issue #49 de fazer uma interface, penso que poderia adicionar isso também, e em resultado ser algo separado desse git talvez
