### ISSUE TITLE
BUG: Página de SO com erro 404

### ISSUE THREAD

**Issue by Rickecr** [OpenDevUFCG/Tamburetei#401]
Ao selecionar a opção `Resumos` no [README](https://github.com/OpenDevUFCG/Tamburetei/blob/master/so/README.md) é redirecionado para uma página inexistente.

**Solução:**
- Mudar o link para onde a opção `Resumos` esta direcionando.
- Mudar para `resumos/README.md`

**Comment by lucasmedeiros** [comment]
Closed via #402
