### ISSUE TITLE
Adicionar resumos de Projeto de Software

### ISSUE THREAD

**Issue by fanny** [OpenDevUFCG/Tamburetei#43]
Adicionar resumos sobre os tópicos abordados durante a disciplina, dando prioridade a explicações amigáveis para pessoas com pouca ou nenhuma experiência com web. Algumas sugestões de tópicos:

- [ ] Padrões de Projeto
- [ ] HTML
- [ ] CSS
- [ ] JavaScript

**Comment by LukeHxH** [comment]
@FannyVieira Acho que, melhor do que fazer resumos de HTML, CSS e JS seria colocar links de cursos básicos/intermediários dessas linguagens, pois seriam coisas gigantescas, e deixar os resumos apenas para os padrões de projetos. No máximo, poderíamos fazer resumos sobre promises, ou até mesmo implementações. O que acha?

**Comment by FannyVieira** [comment]
Concordo, inclusive os links uteis que tem lá, eu 1ue coloquei, mas se tu souber de mais pode complementar

**Comment by FannyVieira** [comment]
Sobre as implementações, acho muito válido também, eu vou me "desatribuir" porque to sem tempo pra fazer, mas concordo que implementações e explicações sobre tópicos bem recorrentes, como promises e callbacks sejam interessantes

**Comment by LukeHxH** [comment]
Outros resumos que seriam interessantes, além de padrões de projetos, seria sobre Web Components, inclusive posso até fazer, ou linkar aquele texto que Dalton passou para ler no período passado. O que acham?
