### ISSUE TITLE
Adicionar implementações úteis de Projeto de Software

### ISSUE THREAD

**Issue by matheusps** [OpenDevUFCG/Tamburetei#45]
Fui monitor de Projeto de Software período passado e uma dificuldade que percebi no pessoal se deve à falta de exemplos bons e simples de implementação com tecnologias frontend, como React, Angular e Vue. Eu poderia contribuir com alguns de React. Alguns exemplos legais:

- [ ] Lista de tarefas
- [X] App de notas
- [ ] Blog simples
- [ ] Mini loja virtual, com carrinho e pesquisa de produtos
- [ ] Formulários de registro e login de usuários

Dúvidas: 
1. Acham pertinente esta issue ? 
2. Se sim, teriam alguns exemplos que poderiam ser adicionados ou retirados ?
3. As implementações devem ser obrigatoriamente em português ?

**Comment by thayannevls** [comment]
Oi @matheusps, acho pertinente sim e a contribuição será bem vinda.

Em relação a linguagem, acho que pode ser tanto português ou inglês, desde que mantenha o padrão. Como essa cadeira é na metade do curso, imagino que as pessoas não tenham dificuldade com inglês.

**Comment by SpinnelSun** [comment]
Também seria bom levantar uns exemplos utilizando HTML, CSS e JS puros. Estou cursando a disciplina nesse período e o uso de frameworks durante o projeto será, muito provavelmente, vetado.

**Comment by matheusps** [comment]
@SpinnelSun,

Podemos adicionar uns exemplos básicos como você descreveu. Mas, não entendi uma coisa... Vocês vão ter que construir aplicações sem usar qualquer biblioteca ou framework ?  🤔

**Comment by SpinnelSun** [comment]
@matheusps yep. Inclusive HTML, CSS e JS estão sendo dados como assunto mesmo. A promessa é que, se a especificação for muito complexa, aí talvez (muito talvez) liberem algum framework.

**Comment by matheusps** [comment]
Quando fui monitor eles também foram dados como assunto primeiro. Aí no projeto pediram com bibliotecas ou frameworks. Mas, de qualquer forma, exemplos puros são bem vindos.

**Comment by LukeHxH** [comment]
Não foi vetado o uso de frameworks front-end no período passado, com exceção de Angular 2, e provavelmente não será vetado nesse. Então, acho que exemplos de frameworks são muito bem-vindos, mas não implementações diretas no repositório, mas sim como links para cursos/sites construídos com tais tecnologias/codepens, etc...

**Comment by alvesmatheus** [comment]
Fechando essa *issue* após editar a #161 para que englobe as duas discussões.
