### ISSUE TITLE
Quais seriam as dificuldades mais comuns em EDA e LEDA? 

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#5]
EDA e LEDA são cadeiras complicadas de discutir, eu mesma estou pagando ainda, se tiver algum veterano que possa opinar

**Comment by JuanBarros2** [comment]
Eu acredito que o mais complicado de se entender é calcular a complexidade de um algoritmo. Os outros assuntos que tem em EDA/LEDA tem visualização na internet pra tudo. Tem uns links que mostram até o passo a passo quando é inserido um item.

**Comment by thayannevls** [comment]
Verdade @JuanBarros2 , acho que a gnt pode incluir alguns exemplos de cálculo de complexidade rápidos

**Comment by FannyVieira** [comment]
Acho que em LEDA, é bom você sempre tentar ser criativo, e pensar em como aplicar aquele algoritmo em algum problema, existem alguns livros e links que podem ajudar, o CodeChef é um ótimo site com questões bem out of the box, o cracking the coding interview também tem umas aplicações legais.
Vou adiciinar os materiais que conheço aos links uteis.

**Comment by thayannevls** [comment]
Obg @FannyVieira  😀
