### ISSUE TITLE
Colocar PDFs de práticas e tutoriais de plp

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#56]
Em PLP, os monitores e professores disponibilizam PDFs com questões e também tutoriais, seria bom ter os links para os mesmos em **linksUteis.md**

**Comment by LukeHxH** [comment]
Acabei de commitar! :p

**Comment by thayannevls** [comment]
Value @LukeHxH :p problema resolvido então

Ei, como no teu repositório de práticas tem os PDFs, acho que poderia tirar daqui, e deixar lá

**Comment by LukeHxH** [comment]
Na verdade, acho que vou tirar de lá e deixar aqui, acho que uma pasta apenas com um README com um link não seria tão útil. O que acha?

**Comment by thayannevls** [comment]
Bem como lá tem as resoluções talvez fizessem mais sentido ficar lá, até pro pessoal que não chegou naquele repositório pelo Tamburetei, entender. Mas não sei kkk fiquei sem saber agr

**Comment by LukeHxH** [comment]
Qualquer coisa, deixa nos dois kkkkk
Acho que não tem problema

**Comment by thayannevls** [comment]
Vou fechar então 😛
