### ISSUE TITLE
Implementações de Prog2

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#6]
Os conceitos que eu acho que poderiam ser mostrados:

- [x] Exemplo básico de herança
- [ ]  Exemplo do padrão Strategy
- [ ] Exemplo de Composição
- [ ] Exemplo de Comparable
- [ ] Exemplos dos tipos de polimorfismo
- [ ] Exemplos usando funcionalidades novas do Java8
- [x] Exemplos de equals, toString e hashCode
- [x] Exemplos de testes com Junit

Claro que um pode se misturar com o outro

**Comment by LukeHxH** [comment]
Vou implementar alguns exemplos de testes com JUnit (que contemple vários casos de uso, incluindo testes para exceções), e colocar um link da apresentação que eu e @SpinnelSun fizemos na monitoria de P2 esse período.

**Comment by LukeHxH** [comment]
Vou ficar responsável por essa Issue, e colocar os exemplos de implementação para cada uma das tarefas da task list. Acho bom realmente fazer uma implementação para cada e não permitir que alguma se misture com outra, pois os alunos muitas vezes procuram por tópicos, e é uma boa ideia que estejam separados e organizados apropriadamente.

**Comment by hericlesme** [comment]
@LukeHxH Você vai ficar responsável por toda a Issue? Posso atribuí-la à você.

**Comment by LukeHxH** [comment]
Sim :)
