### ISSUE TITLE
Adicionar materiais sobre uso do Linux

### ISSUE THREAD

**Issue by fanny** [OpenDevUFCG/Tamburetei#65]
Acho que seria interessante adicionar alguns materiais sobre o Linux, seus comandos, o funcionamento de sua estrutura de arquivos etc. Quando você é novato e está acostumado com o Windows, tudo isso é muito confuso. Vale até também indicar umas *distros* que são mais parecidas com o Windows para que o choque não seja tão grande.

**Comment by FannyVieira** [comment]
aí é que tá, não se encaixa em disciplina nenhuma, aí não sei se a gente deveria criar uma pasta com tópicos extras, interessantes pra computação, que se relacionam com o que a gente vê nas disciplinas, mas não tem nenhuma disciplina sobre isso

**Comment by thayannevls** [comment]
Verdade, acho que poderia criar uma pasta `extras` com materiais que ajudam em diversas disciplinas

**Comment by thayannevls** [comment]
@SpinnelSun to pensando nessa possibilidade de temos pastas que não são necessariamente disciplinas, como essa aqui do `linux`, só não sei bem como manter isso organizar e continuar o padrão que tem no repositório, o que tu acha?

Também tem a possibilidade de que essas coisas deveriam ser um repositório separado

**Comment by SpinnelSun** [comment]
Acho muito válido também, mas seguindo o que tu disse um tempo atrás: teríamos uma pasta `extras` em que se organizaria qualquer coisa que não fosse diretamente ligado à uma disciplina (como coisas pro linux, scripts, etc). Nesse caso, esse diretório precisaria de um `README.md` mais organizadinho que um mero sumário pra explicar o que cada sub-diretório tem, etc e tal.

**Comment by juliobguedes** [comment]
Gente, sei que o conteúdo de SysAdmin (Administração de Sistemas) tem coisa de Shell pra caramba, acho que talvez seja justo adicionar lá, e ai a gente coloca uma "busca" pra tópicos relevantes que estão dentro das pastas (algo a se pensar melhor depois). Vide o [repositório](https://github.com/estacioneto/sys-admin-2018.2) de SysAdmin de @estacioneto, 100% shell

**Comment by tarsojabbes** [comment]
Essa issue será fechada porque foge do escopo do Tamburetei nesse momento. O pessoal dos Guardians tá cuidando desse tópico semestralmente com os feras.
