### ISSUE TITLE
Incluir materiais de cálculo 1

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#7]
O livro de Thomas e as resoluções das questões seriam ideais para incluir nos LinksUteis

**Comment by FannyVieira** [comment]
Algumas ferramentas também, como: wolfram alpha, symbolab, o desmos, que é pra plotar o gráfico da função fornecida.
Alguns fóruns de questões parecidos com o stackoverflow, mas pra matemática, como por exemplo: [math stack exchange](https://math.stackexchange.com/) e [mathoverflow](https://mathoverflow.net/).
Tem um site muito bacana que apesar de não ter uma interface muito amigável  explica as coisas de uma forma bem simples que é o [math is for fun](https://www.mathsisfun.com/calculus/index.html)
Vou criar uma PR pra isso.

**Comment by thayannevls** [comment]
@FannyVieira acho que já tem todos os necessários né? Fecho a issue?

**Comment by FannyVieira** [comment]
Fecha, a medida que o povo pensar em mais, eles adicionam.
