### ISSUE TITLE
Completar cadeiras de p1 para semana do fera

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#71]
Precisamos nos preparar pra semana do fera e listar algumas coisas que precisamos fazer com urgência até lá

- [x] FMCC1
   - [x] Coletar informações sobre FMCCI
   - [x] Visão Geral e Dicas
       - [x] Ementa
       - [x] Visão geral
       - [x] Dicas
   - [x] Extras
   - [x] Links úteis
   - [x] Dificuldades comuns
- [x] IC
   - [x] Coletar informações sobre IC
   - [x] Visão Geral e Dicas
       - [x] Ementa
       - [x] Visão geral
       - [x] Dicas
   - [x] Extras
   - [x] Links úteis
   - [x] Dificuldades comuns

**Comment by guimcarneiro** [comment]
Estou adicionando a visão geral de FMCCI.

**Comment by hericlesme** [comment]
@guimcarneiro talvez ajude ver #103 #104 #110

**Comment by hericlesme** [comment]
@guimcarneiro posso colocar #103 e #104 em andamento, certo?

**Comment by guimcarneiro** [comment]
> @guimcarneiro posso colocar #103 e #104 em andamento, certo?

Sim, sim
