### ISSUE TITLE
Criar Jupyter Notebooks com tutoriais práticos de python

### ISSUE THREAD

**Issue by hericlesme** [OpenDevUFCG/Tamburetei#72]
Acredito que notebooks jupyter são uma boa maneira interativa de visualizar e reproduzir o código. Seria interessante ter alguns para o pessoal praticar. @thayannevls @jonathantvrs

**Comment by hericlesme** [comment]
E acredito que mais simples ainda seria colocá-los de forma pública em instâncias virtuais. É ótimo em questões de praticidade. Assim, o usuário não precisaria instalar nada para executar os notebooks.

Uma boa opção é o [Google Colaboratory](https://colab.research.google.com), e também tem o [Azure Notebooks](https://notebooks.azure.com/).

**Comment by jonathantvrs** [comment]
Concordo que é bem mais prático as instâncias virtuais. Vamos discutir aqui então como vai ser o roteiro. Os notebooks vão ser divididos de que forma? Por unidade? Vai ter um número definido de exemplos ou variado para cada unidade? Na minha opinião devemos focar nas unidades 4, 5, 7 e 9, elas exigem um pouco mais e são as que "prendem" mais nos Minitestes. Pelo que eu pude acompanhar de 2018.2, o problema com laços é o maior, e o legal é que focando nele nós podemos dar uma base muito boa para todas as outras unidades.

**Comment by thayannevls** [comment]
Pode ser por unidade, principalmente focando em explicar estruturas de condição, repetição e etc. Também concordo com @jonathantvrs que deve-se focar nessas unidades mas também adicionaria alguns notebooks simples para o primeiro "Hello World", formatação de string e etc. Os que penso de cara:

- Como fazer hello world
- Estruturas de condição
- Estruturas de repetição
    - While
    - For
    - Recursão ?
- Arrays
   - Criação, manipulação e etc
- Matrizes
   - Criação, iteração, manipulação e etc
- Dicionário 
   - Criação, iteração, manipulação e etc
- Algoritmos de ordenação
    - Explicar eles, mostrar o passo a passo do algoritmo, como o array fica a cada iteração e etc. Tudo isso é facilitado pelos notebooks.

**Comment by thayannevls** [comment]
Se concordarem com os que citei acima, aconselho adicionar como uma task list e ir marcando ela conformo vai fazendo. Vale lembrar que algumas delas já foram feitas, mas estão em arquivos `.py` normais. Não esqueçam de sempre avisar que parte estão fazendo.

@jonathantvrs se tiver algum problema em rodar os notebooks ou aprender a usar eles, pode perguntar por aqui 😄

**Comment by jonathantvrs** [comment]
Muito bom. Na minha opinião a recursão poderia ficar como um "tópico especial"

**Comment by jonathantvrs** [comment]
O que acha? @thayannevls

**Comment by jonathantvrs** [comment]
Sobre os tópicos que listou, posso ir fazendo os três primeiros, até pra ir aprendendo a mexer com os notebooks

**Comment by thayannevls** [comment]
Recursão não é aplicado em nenhuma unidade? Se não for, ficaria bom sim.

Ótimo @jonathantvrs ! Os códigos prontos pode ficar livre para copiar, modificar ou substituir o que já tem. Alguns tem comentários e exemplos que podem ser reaproveitados, mas fica na decisão de quem fazer.

*Outra coisa importante*, se puderem, além de colocarem no Google Colaboratory, coloquem aqui no repositório também em `prog1/tutoriais/`, pois temos pretensões de um dia talvez fazer o repositório ser um site usando Jekyll.

**Comment by jonathantvrs** [comment]
- [ ] Hello World
- [ ] Condicionais
- [ ] Laços de Repetição
- [ ] Arrays
- [ ] Matrizes
- [ ] Dicionário
- [ ] Algoritmos de Ordenação

**Comment by jonathantvrs** [comment]
Tem algum modelo que vocês queiram seguir ou pode ser no estilo que estava sendo feito, acrescentando apenas a melhora na interação?

**Comment by thayannevls** [comment]
Algo [assim](https://nbviewer.jupyter.org/github/jrjohansson/scientific-python-lectures/blob/master/Lecture-4-Matplotlib.ipynb), sempre com explicações e a saída do código.

@hericlesme Vai ter que sair dessa Issue pra trabalhar em outra coisa, ai eu vou assumir ela contigo agora e colocar isso pra frente. Tu tá fazendo algum tutorial, se sim, qual?

**Comment by jonathantvrs** [comment]
Estava vendo uns tutoriais e a própria documentação.

**Comment by jonathantvrs** [comment]
Vou começar a fazer no Google Colabolatory e mando aqui para irmos discutindo

**Comment by thayannevls** [comment]
@jonathantvrs Criei uma PR pra gente ir trabalhando, e adicionei um tutorial básico de estruturas de condição

**Comment by jonathantvrs** [comment]
@thayannevls como que eu faço para commitar nessa PR?

**Comment by jonathantvrs** [comment]
Hello World e Formatação de Strings já estão prontos lá no Google Colab

**Comment by thayannevls** [comment]
@jonathantvrs Atualiza teu fork, e cria uma branch pra essa task. Ai faz uma [*Draft PR*](https://github.blog/2019-02-14-introducing-draft-pull-requests/) pra simbolizar que é um trabalho em andamento, e coloca essa [permissão](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) pra eu poder editar no teu fork.

Depois disso eu vou merjar minha PR na tua, e a gente trabalho pelo teu fork 😄 


Se tu ficou com alguma dúvida nisso, me chama [aqui](https://gitter.im/OpenDevUFCG/Tamburetei)
