### ISSUE TITLE
Site estático simples

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#77]
Implementar um site estático que permita navegar nas disciplinas facilmente, usaremos Gatsby para isso, e ficará disponível https://tamburetei.opendevufcg.org

Também é bom que os arquivos de configurações não fiquem soltos no repositórios, pois pode acabar confundindo e deixando poluído, verei uma solução para isso.

**Comment by hericlesme** [comment]
@thayannevls pq congelou?

**Comment by thayannevls** [comment]
@hericlesme Vou adiar essa task pra depois da semana do fera por causa da lista de prioridades e também porque quero ter mais tempo pra configurar sem mexer muito na estrutura atual do repositório.

**Comment by hericlesme** [comment]
Ah @thayannevls, é do Tamburetei. Confundi com o site do OpenDev.

**Comment by LukeHxH** [comment]
@thayannevls bora acender esse projeto com força?

**Comment by SpinnelSun** [comment]
#descongelado

**Comment by thayannevls** [comment]
Estou revendo a tecnologia a ser usada

**Comment by lucasecdb** [comment]
oi! posso pegar? :grimacing:

**Comment by lucasmedeiros** [comment]
@lucasecdb Claro! :smiley:

**Comment by UmMatias** [comment]
Opa! Queria contribuir, cabe ainda?

**Comment by alvesmatheus** [comment]
@UmMatias entre no nosso [discord](https://discord.gg/xzk3YJ)! @thayannevls @lucasecdb vocês podem sincronizar o trabalho com Matias por lá?

**Comment by thayannevls** [comment]
Olá @UmMatias na última [contribuição](#249) de @lucasecdb foi adicionado [Gatsby](https://gatsbyjs.org) para o site e já conseguimos deployar [aqui](https://tamburetei.opendevufcg.org/prog1/dificuldadesComuns/).

Próximos passos agora é ir construindo esse site e fazendo os componentes necessários usando React. Nos próximos dias irei criar algumas issues com tasks para isso, ficariamos muito felizes se você quiser participar. Entra no discord e fala com a gente no `#tamburetei`

**Comment by thayannevls** [comment]
To fechando essa issue, e criarei outra organizado tudo que tem que ser feito nesses próximos dias.
