### ISSUE TITLE
Criar script que gera uma disciplina nova

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#82]
Contribuidores tem dificuldade em entender os padrões de pastas e que é preciso ter os arquivos padrões em cada disciplina. Pra isso seria bom criar um script que aceite como argumento o nome da disciplina e crie todos os arquivos que são necessários.

O ideal é que o script seja em python ou sh.

**Comment by FannyVieira** [comment]
Eu faço
