### ISSUE TITLE
Slides são materiais permitidos?

### ISSUE THREAD

**Issue by SpinnelSun** [OpenDevUFCG/Tamburetei#83]
Apesar de ser uma ótima fonte de conteúdo, ter slides aqui pode levar os alunos do período vigente a acessar um material desatualizado. Além disso, os próprios professores disponibilizam seus slides em planilhas/drives/canvas/sites.

Assim sendo, é válido tornar slides um material proibido no Tamburetei?

**Comment by JoseRenan** [comment]
Eu acredito que sim, manteríamos aqui apenas materiais feitos por alunos (Resumos, tutoriais e etc), leites e listas de exercício que são materiais de estudo mais "genéricas" e que podem servir de referência independente do estilo de aula do professor

**Comment by JuanBarros2** [comment]
Acredito que não deveria ser colocado slides, pois é um tipo de conteúdo que diverge muito entre professores. Teremos problemas com versões ultrapassadas e com disponibilidade. Outro fato importante é que os professores costumam atualizar alguns slides e recomendam utilizar sempre o que foi indicado em sala (tendo em vista prazos que variam de periodo para periodo). Dessa forma, acredito que é um conteúdo muito dependioso do professor.

**Comment by thayannevls** [comment]
Concordo que não deveria ser colocado, mas é importante propor uma solução pra falta de conteúdo que se teria tirando os slides, que estão sendo a fonte principal de conteúdo de algumas disciplinas.

Um dos exemplos seria fmcc1 e fmcc2.

**Comment by danielmitre** [comment]
Acredito que todos os slides possam ser traduzidos em uma estrutura de texto/tópicos em markdown. Coisas que precisem de visualização podem ser mostradas como imagens e/ou gifs.

É interessante manter ao máximo os conteúdos em markdown, que pode ser visualizado facilmente aqui no github e é facilmente processado pelo Jekyll #77

**Comment by JuanBarros2** [comment]
Sim. É importante ter muito conteúdo em markdown sim. Até porque é um tipo de arquivo muito leve e que não vai impactar no tamanho do repositório quando contribuidores tentarem participar, o que não tem sido o caso de PDFs e arquivos DOCX.

**Comment by danielmitre** [comment]
Na questão de conteúdo desatualizado:
Também é muito mais trabalhoso de se perceber/resolver com arquivos que precisam de mais um software para editar/visualizar. PDF's têm sua utilidade, mas acho que deveriam ser apenas linkados como materiais extra (livros e provas antigas por exemplo) e focar no markdown como conteúdo principal.

> [off]
> Estou pensando em uma ferramenta para agregar questões de concursos/enem, se aqui acabar usando um padrão para publicar questões (principalmente de múltipla escolha), eu posso trabalhar em uma forma para agregar as questões daqui também.
