### ISSUE TITLE
Incluir materiais de probabilidade

### ISSUE THREAD

**Issue by FannyVieira** [OpenDevUFCG/Tamburetei#9]
Com a mudança de grade, a ementa de probabilidade mudou, tornando os leites de probabilidade obsoletos, seria bacana incluir esse novo material.

**Comment by thayannevls** [comment]
Oi @FannyVieira eu to pagando cálculo agr e inclusive to precisando disso :p tu sabe onde conseguir?

**Comment by FannyVieira** [comment]
Eu acredito que tu pode tentar conseguir com xs professorxs de probabilidade, as antigas acho que eles não tem problema em disponibilizar.

**Comment by thayannevls** [comment]
A minha prof não gosta muito de aluno pegando prova antiga 😩
