### ISSUE TITLE
Adicionar tutorial de Entrada e Saída de dados em prog1

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#91]
É preciso fazer um tutorial ensinando o  básico de entrada e saída de dados, já que é um assunto ensinado em Programação 1. 

O que deveria ser abordado:

`raw_input()`, `input()`, `print()` e etc...

Este tutorial deve ser feito em Python Notebooks, e colocado na pasta `tutoriais/`

**Comment by jonathantvrs** [comment]
@thayannevls , quem vai fzer esse? @LukeHxH ?

**Comment by thayannevls** [comment]
@jonathantvrs essa task tá livre, ninguém pegou até agora 😄

**Comment by jonathantvrs** [comment]
então coloca em andamento, vou fazer.
