### ISSUE TITLE
Ideia de scripts para ambientes das disciplinas

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/Tamburetei#95]
Essa ideia foi feita [aqui](https://github.com/Guardians-DSC/cc-scripts) mas foi descontinuada, depois percebi que isso pode ser incluído aqui no tamburetei.

**Comment by JoseRenan** [comment]
Eu acho que seria uma boa ideia a gente contribuir com o repo dos guardians :thinking: e referenciar no readme do tamburetei sobre "você está procurando informações de configuração de ambiente?" alguma coisa desse tipo

**Comment by thayannevls** [comment]
Pode ser @JoseRenan , esse repositório quem começou foi eu, @ArthurFerrao e Douglas, como a gente saiu não sei se tem alguém pra cuidar desse repositório por lá. Poderíamos falar com algum Guardian sobre isso

**Comment by JoseRenan** [comment]
@dfquaresma é guardian, ouvi falar que ele fez PR aqui recentemente ;) KKKKKKKKKKK

**Comment by JoseRenan** [comment]
A gente pode fazer fork aqui no opendev e ficar mandando contrib pra lá tbm

**Comment by thayannevls** [comment]
Sim, sendo que teria que ter algum maintainer lá ai tem que ver se eles tiverem alguém interessado, se não tiver a gente pode passar pra aqui

**Comment by dfquaresma** [comment]
> @dfquaresma é guardian, ouvi falar que ele fez PR aqui recentemente ;) KKKKKKKKKKK

kkkkkkkkkkkkk introduzido à discussão por libre e expontânea invocação asuhaushuashuhasu

**Comment by dfquaresma** [comment]
Xô dá uma revisada nos repositórios do Guardians para ver se já não temos algo parecido. Já comento uma opinião.

**Comment by dfquaresma** [comment]
> Essa ideia foi feita [aqui](https://github.com/Guardians-DSC/cc-scripts) mas foi descontinuada, depois percebi que isso pode ser incluído aqui no tamburetei.

Entendi. Além desse, também existe o [shell-scripts](https://github.com/Guardians-DSC/shell-scripts) que segue nessa linha, mas não com o mesmo direcionamento. 

Acho a proposta extremamente válida e interessante. Acredito que o repositório pode ser mantido pela organização do Guardians, uma vez que por vezes são os Guardians quem ajudam nas configurações dos LCCs, mas acho que aqui (Tamburetei) poderia ter uma referência apontando para lá (cc-scripts). Essa referência apontando para lá poderia estar na descrição das disciplinas.

**Comment by JoseRenan** [comment]
> Essa referência apontando para lá poderia estar na descrição das disciplinas.

Melhor do que eu tinha sugerido então, tipo, cada disciplina, tipo P1, teria lá: caso queira configurar o ambiente, cheque aqui... na visão geral da disciplina

Só me explica uma coisa, o shell-scripts é o que vcs usam nos LCCs né?

**Comment by dfquaresma** [comment]
> > Essa referência apontando para lá poderia estar na descrição das disciplinas.
> 
> Melhor do que eu tinha sugerido então, tipo, cada disciplina, tipo P1, teria lá: caso queira configurar o ambiente, cheque aqui... na visão geral da disciplina
> 
> Só me explica uma coisa, o shell-scripts é o que vcs usam nos LCCs né?

Acredito que sim.

**Comment by dfquaresma** [comment]
@JoseRenan, @thayannevls, vou discutir essa ideia na próxima reunião do Guardians e aviso por aqui o resultado da discussão.

**Comment by thayannevls** [comment]
Massa @dfquaresma, muito obrigada!
